### ISSUE TITLE
Callback after data is loaded

### ISSUE THREAD

**Issue by jeffdeville** [mbrevoort/jquery-facebook-multi-friend-selector#1]
Hey Mike, thanks a ton for writing this.  I'm using it to great effect.  I was wondering if you'd mind slipping in a callback function I could supply in the options once a user's friends are returned.  There are folks out there with ~1000 friends, or slow connections, and I'd like to be able to display a loading message while their friends are being pulled.

**Comment by mbrevoort** [comment]
I hope to get to this in the next couple of days. I've got some related performance improvements as well. Thanks!

**Comment by mbrevoort** [comment]
I just pushed an update that includes a custom event that's fired when the friends container is finished loading. You would bind to the event like this:

> $("#jfmfs-container").bind("jfmfs.friendload.finished", function() { 
>     alert("finished loaded!"); 
> });

**Comment by jeffdeville** [comment]
Nice!  Thank you!
