### ISSUE TITLE
Hover classes not working in Chrome

### ISSUE THREAD

**Issue by joshmosh** [mbrevoort/jquery-facebook-multi-friend-selector#11]
I found a bug with Chrome v10.0.648.205 on OSX 10.6 where the friend selector does not show the hover classes on friend elements in the list. I fixed this by doing the following:

elem.find(".jfmfs-friend:not(.selected)").live(
                'hover', function (ev) {
                    if (ev.type == 'mouseover' || ev.type == 'mouseenter') {
                        $(this).addClass("hover");
                    }
                    if (ev.type == 'mouseout' || ev.type == 'mouseleave') {
                        $(this).removeClass("hover");
                    }
                });

**Comment by Patrickz** [comment]
I just try and I work fine for me.
the issue fixed? If yes, let's close the issue.

**Comment by joshmosh** [comment]
Could have just been my older version of chrome at the time. Seems to be working now for me now too.
