### ISSUE TITLE
Send invitations to selected friends

### ISSUE THREAD

**Issue by kennym** [mbrevoort/jquery-facebook-multi-friend-selector#30]
Is it possible to send invitations or do other interactions with the Social Graph with this plugin?

**Comment by lacco** [comment]
As far as I see it only helps you selecting friends - posting to someone's feed or invite a friend has to be implemented by yourself.

**Comment by kennym** [comment]
I solved this issue by making use of the Facebook JavaScript SDK. The code looks like this:

``` javascript
        var friendSelector = $("#jfmfs-container").data('jfmfs');             
        var user_ids = friendSelector.getSelectedIds().join(',');
        FB.ui({method: 'apprequests',
          message: 'Hey! Join us!',
          to: user_ids, 
        });
```

**Comment by kennym** [comment]
@lacco just saw your answer! Yeah, I figured out that this plugin does not cover that part. Thanks!
