### ISSUE TITLE
Last user selection.

### ISSUE THREAD

**Issue by oivoodoo** [mbrevoort/jquery-facebook-multi-friend-selector#4]
Hi.

I found problem in your demo page. I filtered my friends for seeing for example 4 friends. And then try to select 4 friends in your control. Can't select the any 4 person. Is it bug?

Thanks.

**Comment by mbrevoort** [comment]
I can't reproduce

It will let you select as many friends as specified in the max_selected option. However, if you have already selected friends and then filtered to hide those already selected friends, those still count towards the total. So if max_selected = 15 and you already selected 15 friends, filtered but none the selected friend elements are visible, you won't be able to select anymore.

That's how it's supposed to work. Going to close, if it doesn't work according to that explanation, please provide more details.

Thanks,
Mike
