### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by rweng** [mbrevoort/jquery-facebook-multi-friend-selector#44]
Hi Mike,

is this repository still maintained? If not, could you put a notice at the top of the Readme, if possible with the offer to add other committers to take over?

Robin

**Comment by mbrevoort** [comment]
Sorry, I just haven't been able to keep up. I did put a notice at the top of the Readme. Let me know if you're interested yourself in being a committer.

**Comment by rweng** [comment]
Hi Mike, nope, I am full :( I need something like this, but a bit more generic where the friends can be injected from the outside (be it linkedIn, FB, .. friends). I send you a pull-request when I am finished and you can decide whether to merge it it or keep this repo purely FB.
