### ISSUE TITLE
Filtering the list by typing does not fire the 'inview' event

### ISSUE THREAD

**Issue by jeffdeville** [mbrevoort/jquery-facebook-multi-friend-selector#5]
As a result, the friend images are not displayed, if they were not in the first screen already.  Thank you for working on the speed issues though.  This is a great optimization effort so far, Mike.

**Comment by mbrevoort** [comment]
Fixed issue with filtered friends not properly loading images. Closed by 3c1bd01a3d621df10c399420a994d749467ef370
