### ISSUE TITLE
I18n support

### ISSUE THREAD

**Issue by fe9lix** [mbrevoort/jquery-facebook-multi-friend-selector#6]
Hi,

currently some labels are hard-coded in the JS file ("Start typing a name" etc.). There should be a way to localize all strings, maybe using the options object which is passed to the jfmfs() call.

**Comment by mbrevoort** [comment]
Extracted all text labels into a labels object that can be passed in. Updated README. Closed by 5621255985f052014edd82e72d8d5266674ac58d

**Comment by kalyfe** [comment]
"Start typing a name" is still hard-coded in two places.
You may want to reopen this issue.
