### ISSUE TITLE
Add show()/hide() methods

### ISSUE THREAD

**Issue by fe9lix** [mbrevoort/jquery-facebook-multi-friend-selector#7]
It would be nice if there were additional public methods to show and hide the selector. Currently this has to be done by adding and removing the container-element...

**Comment by mbrevoort** [comment]
Can't you just call show(), hide(), fadeIn(), fadeOut(), etc on the container? For example:
$("#jfmfs-container").show()
$("#jfmfs-container").hide()

There's actually an inner element too so you could also show, hide, etc on the #jfmfs-friend-selector element too:
$("#jfmfs-friend-selector").fadeIn()
$("#jfmfs-friend-selector").fadeOut()

**Comment by fe9lix** [comment]
Yeah, actually, that's what I'm doing right now - it's ok! I just thought that could be part of the public api. How about destroying the selector? If you look at jquery UI, for example, most components have show/hide/destroy methods.
